version: '3'

services:
  app1:
    image: myapp
    networks:
      my_network:
    ports:
      - "8081:80"
  app2:
    image: myapp
    networks:
      my_network:
    ports:
      - "8082:80"
  app3:
    image: myapp
    networks:
      my_network:
    ports:
      - "8083:80"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9090:9090"
    depends_on:
      - app1
      - app2
      - app3
    networks:
      my_network:

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24